package org.example.rest.security.user;

public enum UserAuthority {

    VIEW_HOTEL,
    VIEW_ROOM,
    CREATE_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    CREATE_HOTEL,
    UPDATE_HOTEL,
    DELETE_HOTEL,
    APPROVE_HOTEL,
    SUSPEND_HOTEL,

    VIEW_BOOKING,
    CREATE_BOOKING,
    UPDATE_BOOKING,
    DELETE_BOOKING,
    CONFIRM_BOOKING,
    CANCEL_BOOKING,
    MANAGE_BOOKING_POLICY,
    REQUEST_BOOKING_CANCELLATION,
    APPROVE_BOOKING_CANCELLATION,
    DENY_BOOKING_CANCELLATION,

    VIEW_PAYMENT,
    CREATE_PAYMENT,
    MANAGE_PAYMENT,
    VIEW_REFUND,
    CREATE_REFUND,

    VIEW_CANCELLATION_POLICY,
    CREATE_CANCELLATION_POLICY,
    UPDATE_CANCELLATION_POLICY,
    DELETE_CANCELLATION_POLICY,

    VIEW_EVENT,
    CREATE_EVENT,
    UPDATE_EVENT,
    DELETE_EVENT,

    VIEW_REVIEW,
    CREATE_REVIEW,
    UPDATE_REVIEW,
    DELETE_REVIEW,

    VIEW_EVENT_RESERVATION,
    CREATE_EVENT_RESERVATION,
    UPDATE_EVENT_RESERVATION,
    DELETE_EVENT_RESERVATION,
    CONFIRM_EVENT_RESERVATION,
    CANCEL_EVENT_RESERVATION,
    COMPLETE_EVENT_RESERVATION,
    ATTEND_EVENT_RESERVATION,
    NO_SHOW_EVENT_RESERVATION,

    VIEW_USER,
    UPDATE_USER,
    DELETE_USER,
    SUSPEND_USER,

    VIEW_CONTACT,
    MANAGE_CONTACT,

    VIEW_LOYALTY,
    VIEW_ALL_LOYALTY,

    CREATE_AMENITY,
    UPDATE_AMENITY,
    DELETE_AMENITY,
    VIEW_AMENITY
}